spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: community
    password: msqlpass

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    web:
      pageable:
        default-page-size: 20

  messages:
    basename: messages,errors

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

logging:
  level:
    root: info
    sql: debug
    org.hibernate.orm.jdbc.bind: trace

file:
  image:
    dir: C:/temp-dir/images/